name: Release Windows Executable

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_windows:
    runs-on: windows-latest
    permissions: # <-- Добавьте эту секцию
      contents: write # <-- Разрешить запись в содержимое репозитория (включает релизы)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Важно: укажите точную версию Python, например '3.10' или '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller python-docx

      - name: Build with PyInstaller
        run: pyinstaller --onefile --name "find_duplet" --icon=compinfo.ico find_duplet.py
        shell: cmd

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/find_duplet.exe
          name: Release ${{ github.ref_name }} (Windows)
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}